# .github/workflows/deploy-netlify.yml

name: Deploy to Netlify

on:
  # Run this workflow on pushes to the main branch
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy site to Netlify
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js to use the Netlify CLI
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Install the Netlify CLI
      - name: Install Netlify CLI
        run: npm install netlify-cli -g

      # 4. Run the deploy command
      - name: Deploy to Netlify
        run: netlify deploy --dir=public --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
